# 基本設置
title: Lescoffee
description: 探索各類咖啡豆、風味及自定義混合您的完美咖啡
baseurl: "/coffee"
url: "https://lesyu.github.io"

# GitHub Pages 設置
remote_theme: jekyll/minima  # 使用 remote_theme 而不是 theme

# 構建設置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
