# 基本設置
title: Lescoffee
description: 探索各類咖啡豆、風味及自定義混合您的完美咖啡
baseurl: ""
url: ""

# Jekyll 主題設置
theme: minima  # 使用 minima 主題，這是 GitHub Pages 支援的默認主題
# 其他可選主題：
# theme: jekyll-theme-cayman
# theme: jekyll-theme-minimal
# theme: jekyll-theme-slate

# 構建設置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/