source "https://rubygems.org"

# 移除單獨的 jekyll 和 minima gem
# 使用 github-pages gem 代替
gem "github-pages", group: :jekyll_plugins
gem "jekyll-remote-theme"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end 